#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_65
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR

ls

cd build/libs

ls

nohup java -Xms384m -Xmx412m -jar repo-all.jar ${OPENSHIFT_DIY_IP} ${OPENSHIFT_DIY_PORT} --spring.profiles.active=openshift &
